services:
  web:
    build: .
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - default
    env_file:
      - .env

  db:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - default
